spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console  # H2 Console의 Path
#    # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
#    datasource:
#      driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
#      url: jdbc:h2:mem:testdb  # H2 접속을 위한 URL (H2 Database는 인메모리 DB로, URL은 jdbc:h2:mem:testdb)
#      username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
  profiles:
    include: oauth
#datasource:
#  url: jdbc:h2:mem:testdb

server:
  ssl:
    key-store: classpath:static/keystore.p12
    key-store-password: testpwd
    key-store-type: PKCS12
  port: 443
