APPLE_KEY_ID: Key
APPLE_TEAM_ID: Team
APPLE_CLIENT_ID: com.migusdn.snsLoginExample
APPLE_KEY_PATH: keyPath
oauth2:
  apple:
    auth:
      token-url: https://appleid.apple.com/auth/token
      public-key-url: https://appleid.apple.com/auth/keys
#    redirect-uri: ${APPLE_REDIRECT_URL}
    iss: https://appleid.apple.com
    aud: ${APPLE_CLIENT_ID}
    team-id: ${APPLE_TEAM_ID}
    key:
      id: ${APPLE_KEY_ID}
      path: classpath:/certificate/AuthKey_${APPLE_KEY_ID}.p8

